# training provider schema version 0.1
# https://rx.codesimply.com/
type: //rec
required:
    provider:
        type: //str
    website: //str
optional:
    price-category:  # see price categories listed on website
        type: //any
        of:
            - type: //str
              value: budget
            - type: //str
              value: value
            - type: //str
              value: premium
            - type: //str
              value: exclusive
    previews-available: //bool
    discount-bulk-purchase: //bool
    focus:  # see acronyms listed on website
        type: //arr
        contents: //str  
    trainings:
        type: //rec
        required:
            name: //str
        optional:
            short-description: //str
            length:
                min: 1
                max: 256
            description: //str
            tags:
                type: //arr
                contents: //str
            price: //str
            duration: //int  # in hours 
            with-labs: //bool
            type:  # see price categories listed on website
                type: //any
                of:
                    - type: //str
                      value: online
                    - type: //str
                      value: on-site
                    - type: //str
                      value: private
                    - type: //str
                      value: offline
                    - type: //str
                      value: all